plugins {
	id 'java'
	id 'org.springframework.boot' version '3.4.4'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.nine.baseballdiary'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	// --- 핵심 스프링 부트 스타터 ---
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'
	implementation 'org.springframework.boot:spring-boot-starter-webflux'

	// --- 데이터베이스 ---
	runtimeOnly 'org.postgresql:postgresql'

	// --- Lombok ---
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'

	// --- AWS SDK v2 ---
	implementation platform('software.amazon.awssdk:bom:2.20.26')
	implementation 'software.amazon.awssdk:s3'
	implementation 'software.amazon.awssdk:s3-transfer-manager'
	implementation 'software.amazon.awssdk:apache-client'
	// --- JWT ---
	implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.5'
	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5'

	// --- Selenium (다시 추가) ---
//	implementation 'org.seleniumhq.selenium:selenium-java:4.19.1'
//	implementation 'io.github.bonigarcia:webdrivermanager:5.7.0'

	// --- 기타 라이브러리 ---
	implementation 'org.jsoup:jsoup:1.17.2'
	implementation 'com.google.code.gson:gson:2.10.1'

	// --- 개발 및 테스트 ---
	developmentOnly 'org.springframework.boot:spring-boot-devtools'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

tasks.named('test') {
	useJUnitPlatform()
}