name: Docker Deploy to EC2

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Docker image
        run: docker build --no-cache -t baseball-diary:latest .

      - name: Save Docker image
        run: docker save baseball-diary:latest | gzip > baseball-diary.tar.gz

      - name: Setup SSH Proxy for Bastion
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          BASTION_HOST: ${{ secrets.EC2_HOST }}
          BASTION_USER: ${{ secrets.EC2_USER }}
          BASTION_PORT: ${{ secrets.EC2_PORT }}
          WAS_HOST: ${{ secrets.WAS_HOST }}
          WAS_USER: ${{ secrets.WAS_USER }}
        run: |
          mkdir -p ~/.ssh/
          echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat <<EOT >> ~/.ssh/config
          Host bastion
            HostName ${BASTION_HOST}
            User ${BASTION_USER}
            Port ${BASTION_PORT}
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no

          Host was_server
            HostName ${WAS_HOST}
            User ${WAS_USER}
            ProxyJump bastion
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
          EOT

      - name: Copy files to EC2 WAS Server via Bastion
        run: |
          scp baseball-diary.tar.gz was_server:~/
          scp docker-compose.yml was_server:~/

      - name: Deploy on EC2 WAS Server via Bastion
        run: |
          ssh was_server "
            docker load < baseball-diary.tar.gz
            docker-compose down
            docker-compose up -d
            rm baseball-diary.tar.gz
          "